# примеры API-запросов

@baseUrl = http://localhost:8000/api

# получение датчиков
GET http://127.0.0.1:8001/api/sensor/?all=True
Content-Type: application/json

###

# создание датчика
POST http://127.0.0.1:8001/api/sensor/
Content-Type: application/json

{ 
  "name": "ESP32",
  "description": "Датчик на кухне за"
}

###

# обновление датчика
PATCH http://127.0.0.1:8001/api/sensor/
Content-Type: application/json

{   "id": 1, 
    "description": "Перенес датчик на балкон"
}

###

# добавление измерения
POST http://127.0.0.1:8001/api/measurements/
Content-Type: application/json

{
  "sensor": 1,
  "temperature": 22.3
}

###

# получение информации по датчику
GET http://127.0.0.1:8001/api/sensor/?all=Fallse&id=1
Content-Type: application/json
